apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cr-pipeline-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cr-trigger
      bindings:
        - ref: cr-pipeline-binding
      template:
        ref: cr-pipeline-template
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.service_name.exists() && body.new_version.exists()"
